try{
   console.log("hello")
     console.log(a);
     console.log("ending try")
 }catch (err){
    console.log("handling",err)
}finally{
    console.log("finally");
}

console.log("end")